steps:
  test:
    image: python:3.10
    commands:
      - python -V
      - pip install virtualenv
      - virtualenv venv
      - . venv/bin/activate
      - pip install tox
      - sleep 120
      - tox
